name: Java CI with Gradle

on:
  push:
    branches: [ Main ]
  pull_request:
    branches: [ Main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Gradle
      run: web/.github/workflows/ain.yml
           ./gradlew build
    - name: Run Java Main
      run: javac Main.java && java Main
